<?php

print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n";
print "\n";
print "\n";
print "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
print "<head>\n";
print "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n";
print "<title></title>\n";
print "<meta name=\"keywords\" content=\"\" />\n";
print "<meta name=\"description\" content=\"\" />\n";
print "<link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900\" rel=\"stylesheet\" />\n";
print "<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n";
print "<link href=\"fonts.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n";
print "\n";
print "\n";
print "</head>\n";
print "<body>\n";
print "<div id=\"header-wrapper\">\n";
print "	<div id=\"header\" class=\"container\">\n";
print "		<div id=\"logo\">\n";
print "			<h1><a href=\"#\">SMOK3</a></h1>\n";
print "		</div>\n";
print "		<div id=\"menu\">\n";
print "			<ul>\n";
print "				<li class=\"active\"><a href=\"#\" accesskey=\"1\" title=\"\">Homepage</a></li>\n";
print "				<li><a href=\"#\" accesskey=\"2\" title=\"\">Product</a></li>\n";
print "				<li><a href=\"#\" accesskey=\"3\" title=\"\">About Us</a></li>\n";
print "				<li><a href=\"#\" accesskey=\"5\" title=\"\">Contact Us</a></li>\n";
print "			</ul>\n";
print "		</div>\n";
print "	</div>\n";
print "	<div id=\"banner\" class=\"container\"><span>Cigarette is change<br />\n";
print "		Smoking ease pain</span></div>\n";
print "</div>\n";
print "<div id=\"wrapper\">\n";
print "	<div id=\"staff\" class=\"container\">\n";
print "		<div class=\"title\">\n";
print "			<h2>Our Products</h2>\n";
print "			</div>\n";
print "		<div class=\"boxA\"><img src=\"images/Cigarette.jpg\" width=\"300\" height=\"450\" alt=\"\" /></div>\n";
print "		<div class=\"boxB\"><img src=\"images/Vape.jpg\" width=\"300\" height=\"450\" alt=\"\" /></div>\n";
print "		<div class=\"boxC\"><img src=\"images/Accessories.jpg\" width=\"300\" height=\"450\" alt=\"\" /></div>\n";
print "	</div>\n";
print "	<div id=\"page\" class=\"container\">\n";
print "		<div class=\"boxA\">\n";
print "			<h2>Cigarette<br />\n";
print "				<span></span></h2>\n";
print "			<ul class=\"style4\">\n";
print "				\n";
print "			</ul>\n";
print "		</div>\n";
print "		<div class=\"boxB\">\n";
print "			<h2>Vape<br />\n";
print "				<span> </span></h2>\n";
print "			<ul class=\"style3\">\n";
print "				<li class=\"first\">\n";
print "					\n";
print "				</li>\n";
print "			</ul>\n";
print "		</div>\n";
print "		<div class=\"boxC\">\n";
print "			<h2>Accessories<br />\n";
print "				<span></span></h2>\n";
print "			<ul class=\"style4\">\n";
print "				\n";
print "			</ul>\n";
print "		</div>\n";
print "	</div>\n";
print "	<div id=\"welcome\" class=\"container\">\n";
print "		<div class=\"title\">\n";
print "			<h1>THANK YOU FOR VISITING OUR WEBSITE</h1>\n";
print "		</div>\n";
print "		<p>This is <strong>SMOK3</strong>, a website for people who are interesting in smoking to figure and enjoy. </p>\n";
print "	</div>\n";
print "</div>\n";
print "<div id=\"copyright\" class=\"container\">\n";
print "	<p>© Untitled. All rights reserved. | Photos by <a href=\"http://fotogrph.com/\">Fotogrph</a> | Design by <a href=\"http://templated.co\" rel=\"nofollow\">TEMPLATED</a>.</p>\n";
print "</div>\n";
print "</body>\n";
print "</html>\n";

?>